### ISSUE TITLE
FocalsConv3d usage

### ISSUE THREAD

**Issue by DezeZhao** [dvlab-research/spconv-plus#1]
Hello, it is amazing that your Focals Conv backbone is as the point cloud feature extraction! But I found that the backbone occupies too much GPU memory while I training on RTX 3090 and also slows down the training.

I am very glad to find that you implement **FocalsConv** with CUDA; I also follow your instruction to see examples in file [focal_sparse_conv_cuda.py](https://github.com/dvlab-research/FocalsConv/blob/0c13a75512ecadb339097f64e7d6c0ae32ada12f/OpenPCDet/pcdet/models/backbones_3d/focal_sparse_conv/focal_sparse_conv_cuda.py), but I found no use of `FocalsConv3d`. So I find the source code of `FocalsConv3d` in `spconv` package. But I wonder how I use it correctly in file [spconv_backbone_focal.py](https://github.com/dvlab-research/FocalsConv/blob/0c13a75512ecadb339097f64e7d6c0ae32ada12f/OpenPCDet/pcdet/models/backbones_3d/spconv_backbone_focal.py). I follow the usage of `spconv.SubMConv3d` in `VoxelBackBone8xFocal` class to replace the  `special_spconv_fn` which is for `FocalSparseConv` with `FocalsConv3d` block. But I found that its `forward` function has parameter `ori_feat_num` which I confuse about it, could you help me what the param stand for? 

the source code is as follows:

```
class FocalsConv3d(SparseConvolution):
    def __init__(self,
                 in_channels,
                 out_channels,
                 kernel_size,
                 stride=1,
                 padding=0,
                 dilation=1,
                 groups=1,
                 bias=True,
                 indice_key=None,
                 algo: Optional[ConvAlgo] = None,
                 fp32_accum: Optional[bool] = None,
                 name=None):
        super(FocalsConv3d, self).__init__(3,
                                         in_channels,
                                         out_channels,
                                         kernel_size,
                                         stride,
                                         padding,
                                         dilation,
                                         groups,
                                         bias,
                                         subm=False,
                                         focal=True,
                                         indice_key=indice_key,
                                         algo=algo,
                                         fp32_accum=fp32_accum,
                                         name=name)


forward function in SparseConvolution:
def forward(self, input: SparseConvTensor, mask=None, ori_feat_num=-1, group_map=None):
if FocalsConv3d is called, ori_feat_num should > 0. In KITTI dataset, the param should be 1 or 3? it means orientation feature num? 
```

Another question is that **is it right t**o replace `special_spconv_fn` with `spconv.FocalsConv3d` without any other parameters changed except kernel_size, in/out_channels, stride?

I would appreciate for your reply. Thank you again.

**Comment by yukang2017** [comment]
Hi Deze,

Thanks for your interest in our work. I uploaded the new examples just now. You can find the example from the following codes.

https://github.com/dvlab-research/FocalsConv/blob/master/OpenPCDet/pcdet/models/backbones_3d/spconv_backbone_focal_cuda.py

https://github.com/dvlab-research/FocalsConv/blob/master/OpenPCDet/pcdet/models/backbones_3d/focal_sparse_conv/focal_sparse_conv_cuda.py


Regards,
Yukang Chen

**Comment by yukang2017** [comment]
ori_feat_num means the number of sparse features in the original input sparse features.

**Comment by DezeZhao** [comment]
Wow! I am truly grateful for your help.
