### ISSUE TITLE
Will this repo keep up-to-date with original spconv?

### ISSUE THREAD

**Issue by bigsheep2012** [dvlab-research/spconv-plus#2]
Hello @yukang2017 @yanwei-li 
Thanks for sharing your research work. 
In fact, Spconv is still updating. So, as the title mentioned, will spconv-plus keep updating the spconv part of the spconv-plus repo while original spconv repo updates?

**Comment by yukang2017** [comment]
Hi,

Thanks for your interests in our work. We will try to keep to the latest spconv, but it takes some time. We might finish it in the next month. Thanks for your understanding.


Regards,
Yukang Chen
