### ISSUE TITLE
usage of spconv-plus

### ISSUE THREAD

**Issue by liulin813** [dvlab-research/spconv-plus#3]
Hello, I noticed that there were issues during the use of spconvplus. For example, in the example code, I did not find any corresponding files in the corresponding folders for many referenced libraries.
![image](https://user-images.githubusercontent.com/94374055/230033467-bd78ff5f-4602-4a49-ab87-d07539c246d3.png)

Thank you very much for your reply

**Comment by liulin813** [comment]
Especially the package referenced by the red line below, I did not find this file

**Comment by yukang2017** [comment]
Hi,

This line can be directly removed. It is unneeded. I have updated this line.
https://github.com/dvlab-research/FocalsConv/blob/master/OpenPCDet/pcdet/models/backbones_3d/focal_sparse_conv/focal_sparse_conv_cuda.py

Regards,
Yukang Chen

**Comment by yukang2017** [comment]
For more details, I tried to write a CUDA-version check-repeat operation to replace the pytorch-version checkrepeat for better efficiency. But the actual speed-up is little. Thus, I gave up this operation.

The attached is my trials before. You can try it by yourself if you are interested in it.
[check_repeat.zip](https://github.com/dvlab-research/spconv-plus/files/11160321/check_repeat.zip)

Regards,
Yukang Chen

**Comment by liulin813** [comment]
Thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月5日(星期三) 晚上10:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dvlab-research/spconv-plus] usage of spconv-plus (Issue #3)





 
Hi,
 
This line can be directly removed. It is unneeded. I have updated this line.
 https://github.com/dvlab-research/FocalsConv/blob/master/OpenPCDet/pcdet/models/backbones_3d/focal_sparse_conv/focal_sparse_conv_cuda.py
 
Regards,
 Yukang Chen
